services:
  db:
    image: postgres:16
    container_name: FlydacBD
    restart: always
    environment:
      POSTGRES_DB: FlydacBD
      POSTGRES_USER: sorby_development
      POSTGRES_PASSWORD: sorby_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5480:5432"  # expone la DB a host.docker.internal
    networks:
      - sorbynet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: istock
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgres://sorby_development:sorby_development@host.docker.internal:5480/FlydacBD"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]
    networks:
      - sorbynet

volumes:
  postgres_data:

networks:
  sorbynet:
    driver: bridge
