module.exports ={
    "stock": [
        { "id": 1, "nombre": "Mensulas Ino Flotante" },
        { "id": 2, "nombre": "Bastidor Tablero" },
        { "id": 3, "nombre": "Rollos Corrugados 3/4" },
        { "id": 4, "nombre": "Kalop Conductor Subterraneo 3x1,5 (x125mts)" },
        { "id": 5, "nombre": "Kalop Conductor Subterraneo 3x2,5 (x150mts)" },
        { "id": 6, "nombre": "Rollo Manguera Azul 3/4" },
        { "id": 7, "nombre": "Polinam Caño Pvc T/Manguera 3/4(rollox25Mts)" },
        { "id": 8, "nombre": "M.H Conductor Unipolar 10,00 V/Amarillo" },
        { "id": 9, "nombre": "Epuyen (Te-00450-NG) Cond. Telefonico 4 pares Subt.782" },
        { "id": 10, "nombre": "Kalop Conductor Unipolar 1,5 MM Celeste" },
        { "id": 11, "nombre": "Kalop Conductor Unipolar 1,5MM Rojo" },
        { "id": 12, "nombre": "Kalop Conductor  Unipolar 1,5MM V/Amarillo" },
        { "id": 13, "nombre": "Kalop Conductor Unipolar 1,5MM Blanco" },
        { "id": 14, "nombre": "Kalop Conductor Unipolar 1,5 MM Marron" },
        { "id": 15, "nombre": "Kalop Conductor Unipolar 1,5MM Negro" },
        { "id": 16, "nombre": "Kalop Conductor Unipolar 2,5MM Negro" },
        { "id": 17, "nombre": "Kalop Conductor Unipolar 2,5MM Marron" },
        { "id": 18, "nombre": "Kalop Conductor Unipolar 2,5MM Celeste" },
        { "id": 19, "nombre": "Kalop Conductor Unipolar 2,5MM V/Amarillo" },
        { "id": 20, "nombre": "Kalop Conductor Unipolar 2,5MM Rojo" },
        { "id": 21, "nombre": "Kalop Conductor Unipolar 4MM Rojo" },
        { "id": 22, "nombre": "Kalop Conductor Unipolar 4MM Celeste" },
        { "id": 23, "nombre": "Kalop Conductor Unipolar 4MM V/Amarillo" },
        { "id": 24, "nombre": "Abb Termica Din 2x10" },
        { "id": 25, "nombre": "Abb Termica Din 2x16" },
        { "id": 26, "nombre": "Abb Termica Din 2x20" },
        { "id": 27, "nombre": "Abb Termica Din 4x40" },
        { "id": 28, "nombre": "Commax Portero con Apertura 1 telefono frente Embutir" },
        { "id": 29, "nombre": "Jeluz Platinum Modulo 2 tomas Normalizado +Tierra 2x10A-250VCA Bl" },
        { "id": 30, "nombre": "Jeluz  Platinum Tapon Ciego Blanco" },
        { "id": 31, "nombre": "Jeluz Verona Bastidor Oculto Rectangular" },
        { "id": 32, "nombre": "Jeluz Platinum Tapa Rectangular Blanca" },
        { "id": 33, "nombre": "Jeluz Verona Estanco 2 Mod.Bast y Tapa Transp" },
        { "id": 34, "nombre": "Jeluz Platinum Modulo Punto Blanco 220V 10A" },
        { "id": 35, "nombre": "Jeluz Platinum Modulo Combinacion Blanco 220V 10A" },
        { "id": 36, "nombre": "Jeluz Platinum Modulo Toma 10A Blanco Combinado" },
        { "id": 37, "nombre": "Jeluz Toma de telefonos tipo Americano 4 vias" },
        { "id": 38, "nombre": "Jeluz Platinum Modulo Tv C/Acople pasante pin grueso Blanco" },
        { "id": 39, "nombre": "Jeluz Tapa 5x5 Mignon Blanco" },
        { "id": 40, "nombre": "BmB Curva de Plastico para caño de 1\"" },
        { "id": 41, "nombre": "Sica Disyuntor Diferencial 2x63 A" },
        { "id": 42, "nombre": "Sica Termica 2x10" },
        { "id": 43, "nombre": "Sica Termica 2x15" },
        { "id": 44, "nombre": "Sica Termica 2x20" },
        { "id": 45, "nombre": "Sica Termica 2x63" },
        { "id": 46, "nombre": "Sica Fusible NH 63 A" },
        { "id": 47, "nombre": "Genrod  Caja de pase derivacion (unidades) 15x15" },
        { "id": 48, "nombre": "Genrod Caja de pase 20x20" },
        { "id": 49, "nombre": "Tacsa Precinto 4,6 MM x 100 U-Negro (bolsas de 100 U)" },
        { "id": 50, "nombre": "9 de Julio Conectores de Hierro 3/4 (Bolsas de 100 unidades)" },
        { "id": 51, "nombre": "Gen Rod Caja Termica 8 Bocas Embutir Plastica Ecoo" },
        { "id": 52, "nombre": "Gen Rod Caja Termica 24 Bocas Embutir Plastica Ecoo" },
        { "id": 53, "nombre": "Gen Rod Caja Termica 4 Bocas Embutir Plastica Ecoo" },
        { "id": 54, "nombre": "Gen Rod Jabalina con Toma Cable 1/2 x 1,5 Mts" },
        { "id": 55, "nombre": "Jeluz Platinum Modulo Toma Blanco 20A 250V" },
        { "id": 56, "nombre": "BmB Cupla de 3/4 (Bolsas de 100)" },
        { "id": 57, "nombre": "BmB Cupla de 1 (Bolsa de 50)" },
        { "id": 58, "nombre": "Tapa de Tablero" },
        { "id": 59, "nombre": "Latynplast Tubo exten Universal (unidad)" },
        { "id": 60, "nombre": "Fv Epuyen Ferrum Juego Monocomando para Bañera y ducha 0106/L2" },
        { "id": 61, "nombre": "Clavos 1 1/2 (x bolsa de 1 Kg)" },
        { "id": 62, "nombre": "Peirano Monocomando para pared de Cocina Bilbao  54-130" },
        { "id": 63, "nombre": "Peirano Lavatorio Baño Soria 63-125" },
        { "id": 64, "nombre": "Peirano Marbella Monocomando Cocina Cromo 20-121" },
        { "id": 65, "nombre": "Ferrum Bacha Tori Vasija Chica LK303 B" },
        { "id": 66, "nombre": "Robinet Bronx Bañera C/Transferencia Oxido" },
        { "id": 67, "nombre": "Robinet Bronx Lavatorio Pared Oxido" },
        { "id": 68, "nombre": "Peirano Soria Ducha Embutir C/Transf Monocomando 80-152" },
        { "id": 69, "nombre": "Peirano Black Velvet Ducha Embutir C/Transf C.Cer Negro 80-190 P" },
        { "id": 70, "nombre": "Johnson Acero Desagues de Bacha" },
        { "id": 71, "nombre": "Ideal Deposito de Empotrar con Descarga Dual para Ahorro de Agua" },
        { "id": 72, "nombre": "Roca Slendra Plus (Depositosx2)" },
        { "id": 73, "nombre": "180 Manguera Led 220V x 5 Mts Luz Calida (63025/5/BC)" },
        { "id": 74, "nombre": "Lumicom (5050) Cinta Led Interioir 14,4W Calida 5Mts" },
        { "id": 75, "nombre": "Denka Cinta Aisladora  PVC Vini Tape 10 Mts" },
        { "id": 76, "nombre": "9 de Julio (10004) Caja H Liviana Cuadrada 10x10 Aluminizada Ch20" },
        { "id": 77, "nombre": "9 de Julio (100021) Caja H Liviana Mignon 5x5 Aluminizada Ch20" },
        { "id": 78, "nombre": "Peirano Respuesto Set Prolongador Vastago/Campana A1189" },
        { "id": 79, "nombre": "Prolongador Vastago (los que traen las griferias) (xjuego)" },
        { "id": 80, "nombre": "Matafuego 5 Kg" },
        { "id": 81, "nombre": "9 de Julio Caja H Liviana Octogonal chica Aluminizada Ch 20" },
        { "id": 82, "nombre": "9 de Julio Caja H Liviana Rectangular chica Aluminizada Ch 20" },
        { "id": 83, "nombre": "GenRod Caja p/Monoblock con base NH S/Fusible (085203)" },
        { "id": 84, "nombre": "Bachas Testa 45x32x11 Natural" },
        { "id": 85, "nombre": "Bachas Testa 45x32x11 Oliva" },
        { "id": 86, "nombre": "Compañía Nativa Fiso de Madera" },
        { "id": 87, "nombre": "Tbcin Peines de Alimentacion Bipolar 63A" },
        { "id": 88, "nombre": "LatynFlex Flexible Mallado de Acero Inoxidable macho Giratorio 1/2x35 (xunidad)" },
        { "id": 89, "nombre": "MayorLed Fuente Metalica Linea Slim para perfil de Aluminio y tira Led" },
        { "id": 90, "nombre": "Sika Monotop-107 Seal Impermeabilizante cementicio de Alta Performance (xkg)" },
        { "id": 91, "nombre": "Netcolor Masilla para placas de Yeso Interioir (xKg)" },
        { "id": 92, "nombre": "Casablanca Interioir Mate Balsamo(x lts) Bse B (Abierto)" },
        { "id": 93, "nombre": "Casablanca Interioir Mate Copa Real (x lts) Bse B (Abierto)" },
        { "id": 94, "nombre": "Casablanca Interioir Mate Blanco (xLts) (Abierto)" },
        { "id": 95, "nombre": "Casablanca Esmalte Sintetico MultiAccion 3 en 1 (xlts) (cerrado)" },
        { "id": 96, "nombre": "Casablanca Interioir Mate Base A (xlts) (Abierto)" },
        { "id": 97, "nombre": "Dixilina Diluyente a Base de Aguarras (xlts) (Abierto)" },
        { "id": 98, "nombre": "Sherwin Williams Enduido Plastico Interioir Multiproposito (xlts) (Cerrado)" },
        { "id": 99, "nombre": "Alba Albalatex Formula Avanzada (xlts)" },
        { "id": 100, "nombre": "Solvex Diluyente para Sinteticos a base de Aguarras (xlts) (Abierto)" },
        { "id": 101, "nombre": "Pegalo Sellador Acrilico Blanco (cc)" },
        { "id": 102, "nombre": "Pegalo Silicona Neutra (cc)" },
        { "id": 103, "nombre": "Poximix Mezcla Adhesiva Blanca (xkg)" },
        { "id": 104, "nombre": "Perfiles para Tira Led Per12 para aplicar (x2mts cada uno)" },
        { "id": 105, "nombre": "Perfiles para Tira Led Per14 embutir (x2mts cada uno)" },
        { "id": 106, "nombre": "Perfiles para Tira Led Per11 embutir (x2mts cada uno)" },
        { "id": 107, "nombre": "Perfiles para Tira Led Per32 para aplicar (x1/2mts cada uno)" },
        { "id": 108, "nombre": "Perfiles Bidireccional Exteriores (x2mts cada uno)" },
        { "id": 109, "nombre": "Reel para Spot Blanco de Aplicar (x2mts cada uno)" },
        { "id": 110, "nombre": "Cocina Drean CD5502AI" },
        { "id": 111, "nombre": "Horno Longive H1500XF" },
        { "id": 112, "nombre": "Cocina Electrolux 56DXQ" },
        { "id": 113, "nombre": "Anafe Longive A2600XF" },
        { "id": 114, "nombre": "Vera-Lavatorio Monocomando Alto-Linea Vera (S-B)" },
        { "id": 115, "nombre": "Peirano Soria-Bide Monocomando C/Transferencia-70-152-Linea Soria" },
        { "id": 116, "nombre": "Temple Juego Cocina Monoc.C/Rociador-0412/87-CR" },
        { "id": 117, "nombre": "Riel Embutir Magnetico Slim Negro Microled 3 metros 48V RMS-E-3M" },
        { "id": 118, "nombre": "Riel Embutir Magnetico Slim Negro Macroled 2 metros 48V RMS-E-2M" },
        { "id": 119, "nombre": "Acople Horizontal para Riel de Embutir Magnetico Slim Macroled RMS-CL-E" },
        { "id": 120, "nombre": "Tend 60x120 C&S Sunny In x 1,44 M2" },
        { "id": 121, "nombre": "Tend 60x120 C&S Sunny Out x 1,44M2" },
        { "id": 122, "nombre": "Ilva 45x90 Mediterranea Dig Steel i x 1,22M2" },
        { "id": 123, "nombre": "KlK Mezcla Porcelanato x 30 Kg" },
        { "id": 124, "nombre": "Pastina Prestige Perlato x 5 Kg (x bolsa)" },
        { "id": 125, "nombre": "Temple Juego Cocina Monoc.C/Rociador-0412/87-CR" },
        { "id": 126, "nombre": "Varese-Deposito de Apoyar-Linea Varese" },
        { "id": 127, "nombre": "Varese-Bidet 1AG-Linea Varese" },
        { "id": 128, "nombre": "Varese-Inodoro Largo-Linea Varese" },
        { "id": 129, "nombre": "Daccord Bari-Tapa Mdf Herraje Nylon" },
        { "id": 130, "nombre": "Bari-Deposito de Apoyar Desc Dual-Linea Bari" },
        { "id": 131, "nombre": "Bari-Inodoro Largo-Linea Bari" },
        { "id": 132, "nombre": "Bacha Porcelana Sanitaria" },
        { "id": 133, "nombre": "Pileta Acero 304 Simple-Luxor SI 71A-Simples-71x48,2x21" },
        { "id": 134, "nombre": "Varese/Veneto-Tapa Asiento Uf C/Cierre Suave-Linea Varese" },
        { "id": 135, "nombre": "9 de julio Conector de hierro 1\" (Bolsa de 50)" },
        { "id": 136, "nombre": "Ag.Met Grampa media Omega 3/4 Li.Zincada" },
        { "id": 137, "nombre": "BmB Curva de Plastico para caño 3/4 (Bolson)" },
        { "id": 138, "nombre": "Gen Rod Caja Termica 36 Bocas Embutir Plastica Ecoo" },
        { "id": 139, "nombre": "Gen Rod Jabalina C/Toma Cable 3/8x1Mts" },
        { "id": 140, "nombre": "Jeluz Termica 2x16" },
        { "id": 141, "nombre": "Jeluz Termica 2x20" },
        { "id": 142, "nombre": "Jeluz Disyuntor Diferencial 2x40A" },
        { "id": 143, "nombre": "Schneider Peine Bipolar 80A 12 Polos" },
        { "id": 144, "nombre": "Tacsa Taco 6MMx40 Kit Tarugo+Tornillo Bolsita (xbolsa)" },
        { "id": 145, "nombre": "Tbcin Terminal de cobre estañado 2,5MM" },
        { "id": 146, "nombre": "Tbcin Punta Hueca Negra 1,5MM" },
        { "id": 147, "nombre": "Tecnocom Caño Plastico Rigido Blanco 3/4 (37u)" },
        { "id": 148, "nombre": "Tecnocom Caño Plastico Rigido Blanco 1 (20u)" },
        { "id": 149, "nombre": "Jeluz Termica 2x10" },
        { "id": 150, "nombre": "Gen Rod Caja de Inspeccion Jabalina 15x15 Aislante" },
        { "id": 151, "nombre": "Soria-Lavatorio Pared Embutir Monoc-63-152-Linea Soria" },
        { "id": 152, "nombre": "Codo Aw 90 M-H 50" },
        { "id": 153, "nombre": "Erpa Disco Corte Abrasivo DSA PCP" },
        { "id": 154, "nombre": "Atrim Desague Lienal 45Cm PP onda mate" },
        { "id": 155, "nombre": "Tubo Aw Mac-Hem 1 Mt 50" },
        { "id": 156, "nombre": "Codo Aw 45 H-H 50" },
        { "id": 157, "nombre": "Tapa 3,2 110" },
        { "id": 158, "nombre": "Codo Aw 90 H-H 50" },
        { "id": 159, "nombre": "Erpa Disco Amarillo 115 Segmentado" },
        { "id": 160, "nombre": "Manguito Aw 110" },
        { "id": 161, "nombre": "Boca Aw Acc Horizontal Acome Cerrados 110x63" },
        { "id": 162, "nombre": "Codo Aw 45 H-H 110" },
        { "id": 163, "nombre": "Tapa 3,2 50" },
        { "id": 164, "nombre": "Codo Aw 90 M-H 110" },
        { "id": 165, "nombre": "Ramal Aw 45 110X40 M-H" },
        { "id": 166, "nombre": "Manguito Aw 40" },
        { "id": 167, "nombre": "Manguito Aw 63" },
        { "id": 168, "nombre": "Tubo Aw Mac-Hem 1,00 Mt 110" },
        { "id": 169, "nombre": "Tubo Aw Mac-Hem 1,00 Mt 63" },
        { "id": 170, "nombre": "Codo Aw 90 M-H 40" },
        { "id": 171, "nombre": "Tubo Aw Mac-Hem 1,00 Mt 40" },
        { "id": 172, "nombre": "Erpa Disco Amarillo 230 Segmentado" },
        { "id": 173, "nombre": "Codo Aw 45 H-H 63" },
        { "id": 174, "nombre": "Solucion Losung Lubricante 400 CC" },
        { "id": 175, "nombre": "Codo Aw 90 M-H 63" },
        { "id": 176, "nombre": "Ramal Aw 45 40X40 M-H" },
        { "id": 177, "nombre": "Codo Aw Hembra Corta H-H 40" },
        { "id": 178, "nombre": "Buje Aw M-H 110X63" },
        { "id": 179, "nombre": "Codo Aw 90 H-H 40" },
        { "id": 180, "nombre": "Codo Aw 45 H-H 40" },
        { "id": 181, "nombre": "Tubo Aw Mac-Hem 2,00 Mt 63" },
        { "id": 182, "nombre": "Tapa 3,2 40" },
        { "id": 183, "nombre": "Codo Aw 45 M-H 50" },
        { "id": 184, "nombre": "Tubo Aw Mac-Hem 2,00 Mt 40" },
        { "id": 185, "nombre": "Ramal Aw 45 110X63 M-H" },
        { "id": 186, "nombre": "Boca Aw Ac-Cocina 63x50" },
        { "id": 187, "nombre": "Embudo Aw Acanalado C/Rej 20x20" },
        { "id": 188, "nombre": "Codo Aw 45 M-H 40" },
        { "id": 189, "nombre": "Pileta Aw Poli.15X15 C/Oring" },
        { "id": 190, "nombre": "Codo Aw 45 M-H 110" },
        { "id": 191, "nombre": "O.V Cam Cojinete C/Marco 110 y Tapa" },
        { "id": 192, "nombre": "Ramal Aw 45 63X63 M-H" },
        { "id": 193, "nombre": "O.V CAM Aro Suplementario 10Cm" },
        { "id": 194, "nombre": "Codo Aw 90 H-H 110" },
        { "id": 195, "nombre": "Codo Aw 45 M-H 63" },
        { "id": 196, "nombre": "Ramal Aw 45 110X110 M-H" },
        { "id": 197, "nombre": "Tapas Colector losa Radiante" },
        { "id": 198, "nombre": "Marcos Colector losa Radiante" },
        { "id": 199, "nombre": "GenRod Caja Estanca 10X10" },
        { "id": 200, "nombre": "GenRod Caja para Termica 48 Bocas Embutir Plastica Ecoo" },
        { "id": 201, "nombre": "ICONIA ROCA MONOC. DUCHA C/T CR" },
        { "id": 202, "nombre": "Huferjo Caño Rigido 3/4 x 3mts" },
        { "id": 203, "nombre": "Huferjo Curva Pvc 3/4" },
        { "id": 204, "nombre": "Sassin Peine Bipolar 63A" },
        { "id": 205, "nombre": "Veyka Tarugo y Tornillo 6mm" },
        { "id": 206, "nombre": "Argenplas Conductor Unipolar 1,5 MM Celeste" },
        { "id": 207, "nombre": "Argenplas Conductor Unipolar 1,5 MM Rojo" },
        { "id": 208, "nombre": "Tachos de Pintura Asfaltica 18 Lts" },
        { "id": 209, "nombre": "Amaco Tubo 25mm gris para Desague A.A 2m" },
        { "id": 210, "nombre": "Codo Aw 40 H-H 90" },
        { "id": 211, "nombre": "Codo Aw 40 M-H 90" },
        { "id": 212, "nombre": "Pileta de Patio Bajo Losa Aw" },
        { "id": 213, "nombre": "Buje PP 2 X 11/2" },
        { "id": 214, "nombre": "SD Tubo PVC CL 10 40" },
        { "id": 215, "nombre": "SD Manguito R/M 40X11/2" },
        { "id": 216, "nombre": "SD Buje Corto HH 50X40" },
        { "id": 217, "nombre": "Adhesivo Losung 500 CM3 C/Pincel" },
        { "id": 218, "nombre": "Vulcano Toma de Fondo C/Tapa" },
        { "id": 219, "nombre": "SD Codo 45º 40MM Amanco" },
        { "id": 220, "nombre": "SD Codo 90º 40MM Amanco" },
        { "id": 221, "nombre": "Awaduct Cupla de 63MM" },
        { "id": 222, "nombre": "Awaduct Cupla de 110MM" },
        { "id": 223, "nombre": "Awaduct Tapon 110MM" },
        { "id": 224, "nombre": "Awaduct Tapa 110" },
        { "id": 225, "nombre": "Awaduct Sifon de Pared" },
        { "id": 226, "nombre": "Awaduct Caño 50X50" },
        { "id": 227, "nombre": "Awaduct Caño 40X50" },
        { "id": 228, "nombre": "Amanco Caño 20MM Fusion Verde" },
        { "id": 229, "nombre": "Amanco Caño 25MM Fusion Verde" },
        { "id": 230, "nombre": "Amanco Caño 32MM Fusion Verde" },
        { "id": 231, "nombre": "Embutido C/ placa Led 7W Bt:Alther" },
        { "id": 232, "nombre": "Downligh Medida Linea (1,70) Cocina" },
        { "id": 233, "nombre": "Downligh Medida Linea (1,20) Cocina y Oficina" },
        { "id": 234, "nombre": "Empotrable 10 Luces 275MM 30L 20W Gyon Plus" },
        { "id": 235, "nombre": "Empotrable 5Luces 142MM 30L 10W Gyon Plus" },
        { "id": 236, "nombre": "Empotrable 2 Luces 63 MM 45L 14W Gyon Plus" },
        { "id": 237, "nombre": "Empotrable 1 Luzs 40 MM 45L 2W Gyon Plus" },
        { "id": 238, "nombre": "Aplique de Ext/Int GU10 1X7W Wing" },
        { "id": 239, "nombre": "Unidireccional Aluminio Negro Wing 1" },
        { "id": 240, "nombre": "Plafon 5 Luces 140MM C/Opticas 10W 30 Gyon" },
        { "id": 241, "nombre": "Downligh Perimetral Comedor 3000K (9,00M)" },
        { "id": 242, "nombre": "Downligh Perimetral Pasillo 3000K (3,00M)" },
        { "id": 243, "nombre": "Downligh Perimetral Toilett  (1M)" },
        { "id": 244, "nombre": "Downligh Perimetral Baño 3000K (2,00M)" },
        { "id": 245, "nombre": "Dicrioca PVC 7W GU10 Luz Calida" },
        { "id": 246, "nombre": "Fuente 220-12V" },
        { "id": 247, "nombre": "Te de 20 Fusion verde Amanco" },
        { "id": 248, "nombre": "Te de 25X20 Fusion verde Amanco" },
        { "id": 249, "nombre": "Te de 25X25 Fusion verde Amanco" },
        { "id": 250, "nombre": "Tapa de 25 Fusion Verde Amanco" },
        { "id": 251, "nombre": "Tapa de 32 Fusion Verde Amanco" },
        { "id": 252, "nombre": "Cupla de 32 Fusion verde Amanco" },
        { "id": 253, "nombre": "Te de 32 Fusion verde Amanco" },
        { "id": 254, "nombre": "Codo 25X3/4 R-H Fusion verde Amanco" },
        { "id": 255, "nombre": "Awaduct Cupla de 40MM" },
        { "id": 256, "nombre": "Manguito Aw 40 con rosca 3/4" },
        { "id": 257, "nombre": "Awaduct Caño de 50X1M" },
        { "id": 258, "nombre": "Awaduct Caño de 40X1M" },
        { "id": 259, "nombre": "Codo 25MM  gris Amanco" },
        { "id": 260, "nombre": "Cupla de 25 Fusion  gris Amanco" },
        { "id": 261, "nombre": "Amanco Caño 20MM Fusion Verde" },
        { "id": 262, "nombre": "Codo 20MM  gris Amanco" },
        { "id": 263, "nombre": "Tbcin Punta Hueca gris 2,5MM" },
        { "id": 264, "nombre": "Peirano Vigo Cocina Mes.Monoc C/Duch Extens" },
        { "id": 265, "nombre": "Peirano Fabric Cocina Monocomando Gold" },
        { "id": 266, "nombre": "Robinet Bronx Bidet Oxido" },
        { "id": 267, "nombre": "Roca Inod The Gap LGO Sd Bco" },
        { "id": 268, "nombre": "Roca Depos The Gap 6/3 lts Bco" },
        { "id": 269, "nombre": "Roca Bidet The Gap 1AG C/LL Bco" },
        { "id": 270, "nombre": "Roca Bidet The Gap 3AG C/LL Bco" },
        { "id": 271, "nombre": "Roca Asiento The Gap Inod C/Amort Bco" },
        { "id": 272, "nombre": "Roca Inod The Gap Corto Bco" },
        { "id": 273, "nombre": "Roca Placa de Accionamiento Pl1adual Blanca" },
        { "id": 274, "nombre": "Johns Acces Escurreplatos (Esac Q40)" },
        { "id": 275, "nombre": "Johns Pileta Simple (54x36x24) (E 54)" },
        { "id": 276, "nombre": "Amanco SD Valvula Esferica U/D 40MM" },
        { "id": 277, "nombre": "Vulcano Retorno Orientable C/Aro Desem.50MM" },
        { "id": 278, "nombre": "Vulcano Virola C/Aro Desm" },
        { "id": 279, "nombre": "Vulcano Filtro VC-30 40MM 50 M3 Soplado" },
        { "id": 280, "nombre": "Vulcano Electrobomba Autocebante Bae 0,75HP" },
        { "id": 281, "nombre": "Vulcano Carga Filtrante (VC-30)" },
        { "id": 282, "nombre": "Teflon Alta Densidad 3/4X40" },
        { "id": 283, "nombre": "Lar 11 Tela Esmeril-1 MTS" },
        { "id": 284, "nombre": "Amanco SD Te 40" },
        { "id": 285, "nombre": "Roca Monaco Deposito de Apoyo BCO" },
        { "id": 286, "nombre": "Inodoro Roca Monaco Largo Bco" },
        { "id": 287, "nombre": "Bide Roca Monaco 3 AG Blanco" },
        { "id": 288, "nombre": "JA C37 CR A304 Doble C/Atrb.70.8X37X15" },
        { "id": 289, "nombre": "Bacha Peirano Circular Apoyo 32X14,5 Cm" },
        { "id": 290, "nombre": "Black Velvet Lavatorio Pared C.C 62-190" },
        { "id": 291, "nombre": "Black Velvet Bidet C.C 70-190" },
        { "id": 292, "nombre": "Black Velvet Ducha Embutir C/T C.C Plus 80-190P" },
        { "id": 293, "nombre": "Daccord T/In Monaco Madera H/Nylon" },
        { "id": 294, "nombre": "Black Velvet Monocomando Cocina 20-190" },
        { "id": 295, "nombre": "JA Z52/18 A/430 Simple 52X32X18" },
        { "id": 296, "nombre": "Jeluz Bastidor de Embutir 5X10Cm 3 Modulos" },
        { "id": 297, "nombre": "Caño PVC 3/4" },
        { "id": 298, "nombre": "Caño PVC 1" },
        { "id": 299, "nombre": "Downligh Medida Linea (L) Cocina" },
        { "id": 300, "nombre": "Colgante c/Acrilico Led 1694MM Tasso" },
        { "id": 301, "nombre": "Johns Pileta Doble (85,5x48,2x17,5) S/Dosif (Q 085 a)" },
        { "id": 302, "nombre": "Wd Dokker Vanitory 60 Colg Sint 3Ag Terrarum" },
        { "id": 303, "nombre": "Vulcano Skimmer Boca Ancha P/Hormg.38 Cm 119003" },
        { "id": 304, "nombre": "Vulcano Gabinete P/Eq.Filtrado Vc-30 139995" },
        { "id": 305, "nombre": "Mesadas Retiradas de Solares" },
        { "id": 306, "nombre": "CasaBlanca Pro Interior (xLt)" },
        { "id": 307, "nombre": "Sica Latex" },
        { "id": 308, "nombre": "Microalisado de Cemento" },
        { "id": 309, "nombre": "Masilla Finca" },
        { "id": 310, "nombre": "Loxon Frente" },
        { "id": 311, "nombre": "Miksa Microallisado de Cemento" },
        { "id": 312, "nombre": "Sherwim Williams Quantum (X lt)" },
        { "id": 313, "nombre": "Revomax Yeso (X Kg)" },
        { "id": 314, "nombre": "Revomax Pegamento (X Kg)" },
        { "id": 315, "nombre": "Sherwim Williams Quantum  Cielorraso (X lt)" },
        { "id": 316, "nombre": "Caja de Pase 115X165X110" },
        { "id": 317, "nombre": "Aire Acondicionado" },
        { "id": 318, "nombre": "Unidad Exterioir" },
        { "id": 319, "nombre": "Mensula para Aire Acondicionado" },
        { "id": 320, "nombre": "Caños Galvanizados de 4\" de 1m" },
        { "id": 321, "nombre": "Codo Galvanizado de 4\" a 90" },
        { "id": 322, "nombre": "Codo Galvanizado de 4\" a 45" },
        { "id": 323, "nombre": "Sombrero Galvanizado de 4\"" },
        { "id": 324, "nombre": "Ladrillo Refractario color cemento" },
        { "id": 325, "nombre": "Lajas Refrectarias Simil Cemento" },
        { "id": 326, "nombre": "Mensulas de 60 cm" },
        { "id": 327, "nombre": "Black Velvet Lavatorio C.C 60-190" },
        { "id": 328, "nombre": "Kalop Conductor Unipolar 6MM Rojo" },
        { "id": 329, "nombre": "Kalop Conductor Unipolar 10MM Celeste" },
        { "id": 330, "nombre": "Kalop Conductor Unipolar 10MM V/Amarillo" },
        { "id": 331, "nombre": "Kalop Conductor Unipolar 10MM Rojo" },
        { "id": 332, "nombre": "Reflex 6MM Rojo" },
        { "id": 333, "nombre": "Reflex 2,5MM Rojo" },
        { "id": 334, "nombre": "Reflex 1,5MM Rojo" },
        { "id": 335, "nombre": "Reflex 6MM Verde" },
        { "id": 336, "nombre": "Reflex 4MM Verde" },
        { "id": 337, "nombre": "Reflex 2,5MM Verde" },
        { "id": 338, "nombre": "Reflex 1,5MM Verde" },
        { "id": 339, "nombre": "Reflex 6MM Celeste" },
        { "id": 340, "nombre": "Reflex 2,5MM Celeste" },
        { "id": 341, "nombre": "Reflex 1,5 MM Celeste" },
        { "id": 342, "nombre": "Reflex 1,5MM Negro" },
        { "id": 343, "nombre": "Kalop Conductor Unipolar 6MM Celeste" },
        { "id": 344, "nombre": "Kalop Conductor Unipolar 6MM V/Amarillo" },
        { "id": 345, "nombre": "Reflex 4MM Rojo" },
        { "id": 346, "nombre": "Reflex 4MM Celeste" },
        { "id": 347, "nombre": "Reflex 1,5MM Blanco" },
        { "id": 348, "nombre": "Zocalo EPS Max W Premium (14mm*75mm*2,90m)" },
        { "id": 349, "nombre": "Rollo de Lana de Vidrio" },
        { "id": 350, "nombre": "Rollo Isolant" },
        { "id": 351, "nombre": "Eliane 10x20 Metro White Liso x1M2" },
        { "id": 352, "nombre": "KlK Imp Flex Anclaje Int x25Kg" },
        { "id": 353, "nombre": "Bomba Presuarizadora Vasser Qc Press" },
        { "id": 354, "nombre": "Rollo Manguera Azul 1\"(x35Mts)" },
        { "id": 355, "nombre": "Riel Embutir Magnetico Slim Negro Macroled 1 metros 48V RMS-E-1M" },
        { "id": 356, "nombre": "Perfil Aluminio Embutir Per14x2Mts Tapa Opal p/Tira" },
        { "id": 357, "nombre": "Tapa de Gas Regularizada 40x50" },
        { "id": 358, "nombre": "Caja de Piso Vinilico" },
        { "id": 359, "nombre": "Maquina Ingletadora" }
    ]
}